Added option to skip XI4J window
GrimMaple/JuicedFixes pull request #3
Opened 2021-06-19 12:35 UTC by N1GHT-MAR3

Added an option in the .ini to skip the "XInput support added!" window that pops up when the game launches.

First time doing this sort of thing, so I can't promise that I didn't fuck anything up. Building from the updated master and copy-pasting from the updated release seem to work though.

2021-06-20 12:56 UTC, GrimMaple commented
I'm not sure why this has happened, but `dllmain.cpp` is marked as "Binary" now. Please check what might have gone wrong

2021-06-20 12:57 UTC, GrimMaple commented
Also, please squash the commits and write an appropriate commit message.

2021-06-20 12:58 UTC, GrimMaple requested changes
Thank you for your contribution!
Please adjust some of the things in this PR and I will be glad to merge this into master. If you need any help, feel free to contact me.

2021-06-20 12:58 UTC, GrimMaple commented on JuicedFixes/JuicedFixes.vcxproj
> +<?xml version="1.0" encoding="utf-8"?>
Please revert changes in this file

2021-06-20 12:58 UTC, GrimMaple commented on fixes.ini
> +ShowXI4JWindow = true
This window's initial purpose was to debug that the parch is loaded :) I think the default value sgould be `false`

2021-07-19 17:29 UTC, N1GHT-MAR3 commented
Scrapping the fork for now. Might come back to it once I know what I'm doing.

2021-07-19 17:29 UTC, closed without merging